MAIL_SERVER = 'smtp.gmail.com'
MAIL_USERNAME = 'mica.speaking.time.analysis@gmail.com'
MAIL_PASSWORD = 'sail2019'
MAIL_USE_TLS =  True
MAIL_PORT = 587
ADMINS = ['rajatheb@usc.edu']
SECRET_KEY = 'dev'
MAIL_RECIPIENTS = ['rajathebbar@gmail.com']
MAIL_SUBJECT = 'ITU_speaking_time_numbers'
SCRIPT_DIR = '/Users/rabbeh/Projects/VAD/mica-speech-activity-detection'
OUT_DIR = '/Users/rabbeh/Projects/ITU/flask_proj/mod_proj/app/out_dir'
UPLOAD_FOLDER = '/Users/rabbeh/Projects/ITU/flask_proj/mod_proj/app/data'
REDIS_URL = 'redis://localhost:6379'
QUEUES = ['default']
JOB_TIMEOUT=600
